spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
  cache:
    type: simple
  sql:
    init:
      mode: always
      #schema-locations: classpath*:database/initDB.sql
      #schema-locations: database/initDB.sql
    user:
      name: xanroar
      password: 1232
  jwt:
    key: ${JWT_KEY}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000




#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.username=postgres
#spring.datasource.password=admin
#
#spring.cache.type=simple
#spring.sql.init.mode=always
#
#spring.security.user.name=xanroar
#spring.security.user.password=1232

#spring.sql.init.schema-locations=classpath*:database/initDB.sql
#spring.sql.init.data-locations=classpath*:database/populateDB.sql

