spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      #ddl-auto: update

  cache:
    type: simple
  sql:
    init:
      mode: always
      #schema-locations: database/initDB.sql
  user:
      name: xanroar
      password: 1232
  jwt:
    key: ${JWT_KEY}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000

